import Foundation

enum DefaultWords {
    static let pairs: [WordPair] = [
        WordPair(first: "Chat", second: "Tigre"),
        WordPair(first: "Chien", second: "Loup"),
        WordPair(first: "Lion", second: "Panthère"),
        WordPair(first: "Cheval", second: "Zèbre"),
        WordPair(first: "Vache", second: "Bison"),
        WordPair(first: "Dauphin", second: "Requin"),
        WordPair(first: "Pingouin", second: "Manchot"),
        WordPair(first: "Aigle", second: "Faucon"),
        WordPair(first: "Serpent", second: "Lézard"),
        WordPair(first: "Lapin", second: "Lièvre"),
        WordPair(first: "Plage", second: "Piscine"),
        WordPair(first: "Mer", second: "Lac"),
        WordPair(first: "Rivière", second: "Canal"),
        WordPair(first: "Montagne", second: "Volcan"),
        WordPair(first: "Forêt", second: "Jungle"),
        WordPair(first: "Désert", second: "Savane"),
        WordPair(first: "Île", second: "Presqu’île"),
        WordPair(first: "Ville", second: "Village"),
        WordPair(first: "Hôtel", second: "Camping"),
        WordPair(first: "Parc", second: "Jardin"),
        WordPair(first: "Avion", second: "Hélicoptère"),
        WordPair(first: "Train", second: "Métro"),
        WordPair(first: "Bus", second: "Tramway"),
        WordPair(first: "Voiture", second: "Moto"),
        WordPair(first: "Vélo", second: "Trottinette"),
        WordPair(first: "Bateau", second: "Sous-marin"),
        WordPair(first: "Taxi", second: "VTC"),
        WordPair(first: "Autoroute", second: "Nationale"),
        WordPair(first: "Gare", second: "Aéroport"),
        WordPair(first: "Tunnel", second: "Pont"),
        WordPair(first: "Pizza", second: "Quiche"),
        WordPair(first: "Burger", second: "Kebab"),
        WordPair(first: "Pâtes", second: "Riz"),
        WordPair(first: "Frites", second: "Chips"),
        WordPair(first: "Crêpe", second: "Gaufre"),
        WordPair(first: "Croissant", second: "Pain au chocolat"),
        WordPair(first: "Glace", second: "Sorbet"),
        WordPair(first: "Gâteau", second: "Tarte"),
        WordPair(first: "Café", second: "Thé"),
        WordPair(first: "Coca-Cola", second: "Pepsi"),
        WordPair(first: "Pomme", second: "Poire"),
        WordPair(first: "Orange", second: "Mandarine"),
        WordPair(first: "Fraise", second: "Framboise"),
        WordPair(first: "Pastèque", second: "Melon"),
        WordPair(first: "Pêche", second: "Abricot"),
        WordPair(first: "Carotte", second: "Courgette"),
        WordPair(first: "Tomate", second: "Poivron"),
        WordPair(first: "Poulet", second: "Dinde"),
        WordPair(first: "Saumon", second: "Truite"),
        WordPair(first: "Beurre", second: "Margarine"),
        WordPair(first: "Téléphone", second: "Tablette"),
        WordPair(first: "Ordinateur", second: "Console"),
        WordPair(first: "Télévision", second: "Écran"),
        WordPair(first: "Clavier", second: "Piano"),
        WordPair(first: "Souris", second: "Trackpad"),
        WordPair(first: "Casque", second: "Écouteurs"),
        WordPair(first: "Appareil photo", second: "Caméra"),
        WordPair(first: "Chargeur", second: "Batterie"),
        WordPair(first: "Wi-Fi", second: "Bluetooth"),
        WordPair(first: "Netflix", second: "Disney+"),
        WordPair(first: "Football", second: "Rugby"),
        WordPair(first: "Tennis", second: "Badminton"),
        WordPair(first: "Basket", second: "Handball"),
        WordPair(first: "Volley", second: "Beach-volley"),
        WordPair(first: "Ski", second: "Snowboard"),
        WordPair(first: "Boxe", second: "MMA"),
        WordPair(first: "Course", second: "Marche"),
        WordPair(first: "Piscine", second: "Aquagym"),
        WordPair(first: "Karting", second: "Formule 1"),
        WordPair(first: "Billard", second: "Bowling"),
        WordPair(first: "Film", second: "Série"),
        WordPair(first: "Cinéma", second: "Théâtre"),
        WordPair(first: "Acteur", second: "Chanteur"),
        WordPair(first: "Guitare", second: "Basse"),
        WordPair(first: "Piano", second: "Orgue"),
        WordPair(first: "Rap", second: "Rock"),
        WordPair(first: "Photo", second: "Vidéo"),
        WordPair(first: "Livre", second: "Manga"),
        WordPair(first: "Journal", second: "Magazine"),
        WordPair(first: "Radio", second: "Podcast"),
        WordPair(first: "École", second: "Université"),
        WordPair(first: "Professeur", second: "Élève"),
        WordPair(first: "Police", second: "Gendarmerie"),
        WordPair(first: "Médecin", second: "Infirmier"),
        WordPair(first: "Avocat", second: "Juge"),
        WordPair(first: "Restaurant", second: "Cafétéria"),
        WordPair(first: "Banque", second: "Assurance"),
        WordPair(first: "Supermarché", second: "Épicerie"),
        WordPair(first: "Boulangerie", second: "Pâtisserie"),
        WordPair(first: "Pharmacie", second: "Hôpital"),
        WordPair(first: "Lit", second: "Canapé"),
        WordPair(first: "Chaise", second: "Fauteuil"),
        WordPair(first: "Four", second: "Micro-ondes"),
        WordPair(first: "Frigo", second: "Congélateur"),
        WordPair(first: "Douche", second: "Baignoire"),
        WordPair(first: "Chemise", second: "T-shirt"),
        WordPair(first: "Jean", second: "Jogging"),
        WordPair(first: "Basket", second: "Chaussure"),
        WordPair(first: "Bonnet", second: "Casquette"),
        WordPair(first: "Sac à dos", second: "Valise")
    ]
}
